# Generated by Django 5.2.7 on 2025-12-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table=None,
        ),
    ]
